"""altered restaurant table

Revision ID: 2c352b9b1c58
Revises: 4811c021c1d2
Create Date: 2023-09-23 17:29:53.864713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c352b9b1c58'
down_revision = '4811c021c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
