"""altered tables

Revision ID: 4811c021c1d2
Revises: 602ea86cab9b
Create Date: 2023-09-23 17:17:25.860389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4811c021c1d2'
down_revision = '602ea86cab9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(), nullable=True))
        batch_op.drop_column('ingridients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingridients', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
